# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    groups:
      patch:
        exclude-patterns:
          - "dioxus*"
        update-types:
          - "patch"
      minor:
        exclude-patterns:
          - "dioxus*"
        update-types:
          - "minor"

      dioxus-patch:
        patterns:
          - "dioxus*"
        update-types:
          - "patch"
      dioxus-minor:
        patterns:
          - "dioxus*"
        update-types:
          - "minor"
      dioxus-major:
        patterns:
          - "dioxus*"
        update-types:
          - "major"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    groups:
      dev-dependencies-patch:
        dependency-type: "development"
        update-types:
          - "patch"
      dev-dependencies-minor:
        dependency-type: "development"
        update-types:
          - "minor"

      prod-dependencies-patch:
        dependency-type: "production"
        update-types:
          - "patch"
      prod-dependencies-minor:
        dependency-type: "production"
        update-types:
          - "minor"
